### ISSUE TITLE
Could you please add Readme

### ISSUE THREAD

**Issue by xerosanyam** [camerb/AHKs#2]
Please add Readme so that anyone can use your AHK, it would be great if you provide readme for most used ahk scripts of yours. Thanks :)

**Comment by Chunjee** [comment]
camerb hasn't logged onto github in years. Lets see what happens I guess.

**Comment by camerb** [comment]
There is already a readme file for the AHKs repo. Are you asking for me to add a list of my frequently used AHKs to that existing file?

**Comment by camerb** [comment]
No response, closing issue.
